apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k9s
subjects: |
  {{- range .Values.users}}
  - kind: User
    name: {{ . -}}
    apiGroup: rbac.authorization.k8s.io
  {{ end }}
roleRef:
  kind: ClusterRole
  name: k9s
  apiGroup: rbac.authorization.k8s.io