apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
        - name: external-dns
          image: k8s.gcr.io/external-dns/external-dns:v0.7.3
          args:
            - --source=service
            - --source=ingress
            # will make ExternalDNS see only the hosted zones matching provided domain
            # omit to process all available hosted zones
            - --domain-filter={{ .Values.domain }}
            - --provider=aws
            # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
            - --policy={{ .Values.policy }}
            # only look at public hosted zones (valid values are public, private or no value for both)
            - --aws-zone-type={{ .Values.zonetype }}
            - --registry=txt
            - --txt-owner-id={{ .Values.zoneid }}
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files
