apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: {{ .Values.nodearn }}
      username: system:node:{{`{{EC2PrivateDNSName}}`}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    {{- range .Values.users }}
    {{- $user := . -}}
    {{- with $ }}
    - userarn: arn:aws:iam::{{ .Values.accnum }}:user/{{ $user }}
      username: {{ $user }}
      groups:
        - system:masters
    {{- end }}
    {{- end }}